{{- $root := . -}}
{{- $envPrefix := print "/" $root.Release.Name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $root.Release.Name }}-ingress-def
  namespace: {{ $root.Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: {{ $envPrefix }}/$1
spec:
  rules:
  - host: "home.coopstools.com"
    http:
      paths:
      {{- range .Values.deployments }}
      - path: {{ $envPrefix }}{{ .path_prefix }}/(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .name }}-svc
            port:
              number: 80
      {{- if and (not .path_prefix) (eq $envPrefix "/main") }}
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .name }}-svc
            port:
              number: 80
      {{- end }}
      {{- end -}}
