apiVersion: v1
kind: ServiceAccount
metadata:
  name: ns-ctrl-svc-acc #Nice and consuing name: namespace-controller-service-account
  namespace: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modify-ns
  namespace: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: modify-ns-to-svc-acc-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: ns-ctrl-svc-acc
    namespace: {{ .Release.Name }}
roleRef:
  kind: ClusterRole
  name: modify-ns
  apiGroup: rbac.authorization.k8s.io
