{{- $root := . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-ingress
  namespace: {{ $root.Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: "home.coopstools.com"
    http:
      paths:
      {{- range .Values.deployments }}
      - path: /{{ $root.Release.Name }}{{ .path_prefix }}/(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .name }}-svc
            port:
              number: 80
      {{- end }}
