replicaCount: 1
pullPolicy: IfNotPresent
deployments:
- name: user-api
  image: ghcr.io/coopstools-homebrew/shadows-of-the-forgotten
  tag: v1.0.0
  path_prefix: "/user"
- name: user-app
  image: ghcr.io/coopstools-homebrew/elven-far-seeing-stone
  tag: v1.0.0
  port: 80
- name: ns-ctrl
  image: ghcr.io/coopstools-homebrew/binary-neutron-stars
  tag: v1.0.0
  path_prefix: "/ns"
  service_account_name: ns-ctrl-svc-acc
