replicaCount: 1
pullPolicy: IfNotPresent
deployments:
- name: user-api
  image: ghcr.io/coopstools-homebrew/shadows-of-the-forgotten
  tag: v1.0.1
  path_prefix: "/user"
- name: user-app
  image: ghcr.io/coopstools-homebrew/elven-far-seeing-stone
  tag: v1.0.0
  port: 80
- name: ns-ctrl
  image: ghcr.io/coopstools-homebrew/binary-neutron-stars
  tag: v1.0.0
  path_prefix: "/ns"
  service_account_name: ns
- name: the-federation
  image: ghcr.io/coopstools-homebrew/the-federation
  tag: v0.0.5
  path_prefix: "/federation"
  service_account_name: node

service_accounts:
- name: "ns"
  resource: namespaces
  resource_verbs:
  - get
  - list
  - delete
- name: "node"
  resource: nodes
  resource_verbs:
  - top
  - get
  - describe
  - list
  - watch
