name: Helm CD

on:
  push:
    branches: [ dev-* ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Helm Version
        run: helm version
      - name: Get branch name
        env:
          BRANCH_NAME: ${{ github.base_ref }}
        run: echo $BRANCH_NAME
      - name: Pull k8s Credentials
        env:
          TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          K8S_ID: ${{ secrets.DIGITALOCEAN_K8S_CLUSTER_ID }}
        run: |
          curl -H "Authorization: Bearer $TOKEN" "https://api.digitalocean.com/v2/kubernetes/clusters/$K8S_ID/kubeconfig" > k8s_config
      - name: Deploy with Helm
        env:
          KUBECONFIG: k8s_config
          BRANCH_NAME: ${{ github.base_ref }}
        run: helm update --install $BRANCH_NAME ./dev_env
