name: Helm CD

on:
  push:
    branches: [ dev-* ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Helm Version
        run: helm version
      - name: Extract branch name
        shell: bash
        run: echo "##[set-env name=BRANCH_NAME;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Display branch name
        run: echo "The branch is " $BRANCH_NAME
      - name: Pull k8s Credentials
        env:
          TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          K8S_ID: ${{ secrets.DIGITALOCEAN_K8S_CLUSTER_ID }}
        run: |
          curl -H "Authorization: Bearer $TOKEN" "https://api.digitalocean.com/v2/kubernetes/clusters/$K8S_ID/kubeconfig" > k8s_config
      - name: Deploy with Helm
        env:
          KUBECONFIG: k8s_config
        run: helm upgrade --install $BRANCH_NAME ./dev_env
