name: CD Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get pwd
        run: pwd
      - name: Pull k8s Credentials
        env:
          TOKEN: {{ secrets.DIGITALOCEAN_API_TOKEN }}
          K8S_ID: {{ secrets.DIGITALOCEAN_K8S_CLUSTER_ID }}
        run: curl -H "Authorization: Bearer $TOKEN" "https://api.digitalocean.com/v2/kubernetes/clusters/$K8S_ID/kubeconfig" > k8s_config
      - name: Pull pods
        env:
          KUBECONFIG: k8s_config
        run: kubectl get pods
