name: CI Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get pwd
        run: pwd
      - name: Pull k8s Credentials
        run: curl -H "Authorization: Bearer {{ secrets.DIGITALOCEAN_API_TOKEN }}" https://api.digitalocean.com/v2/kubernetes/clusters/{{ secrets.DIGITALOCEAN_K8S_CLUSTER_ID }}/kubeconfig > k8s_config
      - name: Pull pods
        env:
          KUBECONFIG: k8s_config
        run: kubectl get pods
