name: Helm CD on main

on:
  push:
    branches: [ main, dev-* ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Helm Version
        run: helm version
      - name: Extract branch name
        env:
          QUALIFIED_BRANCH: ${{ github.ref }}
        run: echo "::set-output name=BRANCH_NAME::$(echo ${QUALIFIED_BRANCH#refs/heads/})"
        id: extract_branch
      - name: Display branch name
        env:
          QUALIFIED_BRANCH: ${{ github.ref }}
          BRANCH_NAME: ${{ steps.extract_branch.outputs.BRANCH_NAME }}
        run: echo "The branch is $BRANCH_NAME from $QUALIFIED_BRANCH"
      - name: Pull k8s Credentials
        env:
          HB_KUBECONFIG: ${{ secrets.HOMEBREW_KUBE_CONFIG }}
        run: |
          echo $HB_KUBECONFIG | base64 -d > k8s_config
      - name: Deploy with Helm
        env:
          KUBECONFIG: k8s_config
          BRANCH_NAME: ${{ steps.extract_branch.outputs.BRANCH_NAME }}
        run: helm upgrade --install $BRANCH_NAME ./helm_deploy
