name: Manual CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        env:
          BRANCH_NAME: ${{ github.base_ref }}
        run: echo $BRANCH_NAME
      - name: Pull k8s Credentials
        env:
          TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          K8S_ID: ${{ secrets.DIGITALOCEAN_K8S_CLUSTER_ID }}
        run: |
          curl -H "Authorization: Bearer $TOKEN" "https://api.digitalocean.com/v2/kubernetes/clusters/$K8S_ID/kubeconfig" > k8s_config
      - name: Apply k8s scripts
        env:
          KUBECONFIG: k8s_config
        run: |
          kubectl apply -f ./kubectl_deploy/namespace.yaml
          kubectl apply -f ./kubectl_deploy/namespace_ctrl_role.yaml
          kubectl apply -f ./kubectl_deploy/namespace_ctrl.yaml
          kubectl apply -f ./kubectl_deploy/users_api.yaml
          kubectl apply -f ./kubectl_deploy/users_app.yaml
          kubectl apply -f ./kubectl_deploy/users_ingress.yaml
